# coding: utf-8

"""
    WebLink API

    For documentation about this API, please visit https://developer.paylocity.com/integrations/reference/weblink-overview

    The version of the OpenAPI document: v2
    Contact: webservices@paylocity.com
    Generated by: https://konfigthis.com
"""

from paylocity_python_sdk.paths.v2_companies_company_id_employees.post import AddToPaylocity
from paylocity_python_sdk.paths.v2_companies_company_id_employees.get import GetAllEmployees
from paylocity_python_sdk.paths.v2_companies_company_id_employees_employee_id.get import GetEmployeeData
from paylocity_python_sdk.paths.v2_companies_company_id_employees_employee_id.patch import UpdateEmployeeData
from paylocity_python_sdk.apis.tags.employee_api_raw import EmployeeApiRaw


class EmployeeApi(
    AddToPaylocity,
    GetAllEmployees,
    GetEmployeeData,
    UpdateEmployeeData,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: EmployeeApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = EmployeeApiRaw(api_client)
