import typing_extensions

from paylocity_python_sdk.paths import PathValues
from paylocity_python_sdk.apis.paths.v1_employee import V1Employee
from paylocity_python_sdk.apis.paths.v1_company_company_id_employee_employee_id import V1CompanyCompanyIdEmployeeEmployeeId
from paylocity_python_sdk.apis.paths.v1_update_employee import V1UpdateEmployee
from paylocity_python_sdk.apis.paths.v1_deduction import V1Deduction
from paylocity_python_sdk.apis.paths.v1_companies_company_id_employees_employee_id_deductions_deduction_code_start_date import V1CompaniesCompanyIdEmployeesEmployeeIdDeductionsDeductionCodeStartDate
from paylocity_python_sdk.apis.paths.v1_companies_company_id_employees_employee_id_deductions import V1CompaniesCompanyIdEmployeesEmployeeIdDeductions
from paylocity_python_sdk.apis.paths.v1_companies_company_id_employees_employee_id_deductions_deduction_code import V1CompaniesCompanyIdEmployeesEmployeeIdDeductionsDeductionCode
from paylocity_python_sdk.apis.paths.v1_companies_company_id_onboarding_employees import V1CompaniesCompanyIdOnboardingEmployees
from paylocity_python_sdk.apis.paths.v1_companies_company_id_employees_employee_id_local_taxes_tax_code import V1CompaniesCompanyIdEmployeesEmployeeIdLocalTaxesTaxCode
from paylocity_python_sdk.apis.paths.v1_companies_company_id_employees_employee_id_local_taxes import V1CompaniesCompanyIdEmployeesEmployeeIdLocalTaxes
from paylocity_python_sdk.apis.paths.v2_companies_company_id_employees_employee_id_additional_rates import V2CompaniesCompanyIdEmployeesEmployeeIdAdditionalRates
from paylocity_python_sdk.apis.paths.v2_credentials_secrets import V2CredentialsSecrets
from paylocity_python_sdk.apis.paths.v2_companies_company_id_codes_code_resource import V2CompaniesCompanyIdCodesCodeResource
from paylocity_python_sdk.apis.paths.v2_companies_company_id_openapi import V2CompaniesCompanyIdOpenapi
from paylocity_python_sdk.apis.paths.v2_companies_company_id_customfields_category import V2CompaniesCompanyIdCustomfieldsCategory
from paylocity_python_sdk.apis.paths.v2_companies_company_id_employees_employee_id_direct_deposit import V2CompaniesCompanyIdEmployeesEmployeeIdDirectDeposit
from paylocity_python_sdk.apis.paths.v2_companies_company_id_employees_employee_id_earnings import V2CompaniesCompanyIdEmployeesEmployeeIdEarnings
from paylocity_python_sdk.apis.paths.v2_companies_company_id_employees_employee_id_earnings_earning_code_start_date import V2CompaniesCompanyIdEmployeesEmployeeIdEarningsEarningCodeStartDate
from paylocity_python_sdk.apis.paths.v2_companies_company_id_employees_employee_id_earnings_earning_code import V2CompaniesCompanyIdEmployeesEmployeeIdEarningsEarningCode
from paylocity_python_sdk.apis.paths.v2_companies_company_id_employees_employee_id_emergency_contacts import V2CompaniesCompanyIdEmployeesEmployeeIdEmergencyContacts
from paylocity_python_sdk.apis.paths.v2_companies_company_id_employees_employee_id_benefit_setup import V2CompaniesCompanyIdEmployeesEmployeeIdBenefitSetup
from paylocity_python_sdk.apis.paths.v2_weblinkstaging_companies_company_id_employees_newemployees import V2WeblinkstagingCompaniesCompanyIdEmployeesNewemployees
from paylocity_python_sdk.apis.paths.v2_companies_company_id_employees import V2CompaniesCompanyIdEmployees
from paylocity_python_sdk.apis.paths.v2_companies_company_id_employees_employee_id import V2CompaniesCompanyIdEmployeesEmployeeId
from paylocity_python_sdk.apis.paths.v2_companies_company_id_employees_employee_id_local_taxes import V2CompaniesCompanyIdEmployeesEmployeeIdLocalTaxes
from paylocity_python_sdk.apis.paths.v2_companies_company_id_employees_employee_id_local_taxes_tax_code import V2CompaniesCompanyIdEmployeesEmployeeIdLocalTaxesTaxCode
from paylocity_python_sdk.apis.paths.v2_companies_company_id_employees_employee_id_nonprimary_state_tax import V2CompaniesCompanyIdEmployeesEmployeeIdNonprimaryStateTax
from paylocity_python_sdk.apis.paths.v2_companies_company_id_employees_employee_id_paystatement_details_year_check_date import V2CompaniesCompanyIdEmployeesEmployeeIdPaystatementDetailsYearCheckDate
from paylocity_python_sdk.apis.paths.v2_companies_company_id_employees_employee_id_paystatement_details_year import V2CompaniesCompanyIdEmployeesEmployeeIdPaystatementDetailsYear
from paylocity_python_sdk.apis.paths.v2_companies_company_id_employees_employee_id_paystatement_summary_year_check_date import V2CompaniesCompanyIdEmployeesEmployeeIdPaystatementSummaryYearCheckDate
from paylocity_python_sdk.apis.paths.v2_companies_company_id_employees_employee_id_paystatement_summary_year import V2CompaniesCompanyIdEmployeesEmployeeIdPaystatementSummaryYear
from paylocity_python_sdk.apis.paths.v2_companies_company_id_employees_employee_id_primary_state_tax import V2CompaniesCompanyIdEmployeesEmployeeIdPrimaryStateTax
from paylocity_python_sdk.apis.paths.v2_companies_company_id_employees_employee_id_sensitivedata import V2CompaniesCompanyIdEmployeesEmployeeIdSensitivedata

PathToApi = typing_extensions.TypedDict(
    'PathToApi',
    {
        PathValues.V1_EMPLOYEE: V1Employee,
        PathValues.V1_COMPANY_COMPANY_ID_EMPLOYEE_EMPLOYEE_ID: V1CompanyCompanyIdEmployeeEmployeeId,
        PathValues.V1_UPDATEEMPLOYEE: V1UpdateEmployee,
        PathValues.V1_DEDUCTION: V1Deduction,
        PathValues.V1_COMPANIES_COMPANY_ID_EMPLOYEES_EMPLOYEE_ID_DEDUCTIONS_DEDUCTION_CODE_START_DATE: V1CompaniesCompanyIdEmployeesEmployeeIdDeductionsDeductionCodeStartDate,
        PathValues.V1_COMPANIES_COMPANY_ID_EMPLOYEES_EMPLOYEE_ID_DEDUCTIONS: V1CompaniesCompanyIdEmployeesEmployeeIdDeductions,
        PathValues.V1_COMPANIES_COMPANY_ID_EMPLOYEES_EMPLOYEE_ID_DEDUCTIONS_DEDUCTION_CODE: V1CompaniesCompanyIdEmployeesEmployeeIdDeductionsDeductionCode,
        PathValues.V1_COMPANIES_COMPANY_ID_ONBOARDING_EMPLOYEES: V1CompaniesCompanyIdOnboardingEmployees,
        PathValues.V1_COMPANIES_COMPANY_ID_EMPLOYEES_EMPLOYEE_ID_LOCAL_TAXES_TAX_CODE: V1CompaniesCompanyIdEmployeesEmployeeIdLocalTaxesTaxCode,
        PathValues.V1_COMPANIES_COMPANY_ID_EMPLOYEES_EMPLOYEE_ID_LOCAL_TAXES: V1CompaniesCompanyIdEmployeesEmployeeIdLocalTaxes,
        PathValues.V2_COMPANIES_COMPANY_ID_EMPLOYEES_EMPLOYEE_ID_ADDITIONAL_RATES: V2CompaniesCompanyIdEmployeesEmployeeIdAdditionalRates,
        PathValues.V2_CREDENTIALS_SECRETS: V2CredentialsSecrets,
        PathValues.V2_COMPANIES_COMPANY_ID_CODES_CODE_RESOURCE: V2CompaniesCompanyIdCodesCodeResource,
        PathValues.V2_COMPANIES_COMPANY_ID_OPENAPI: V2CompaniesCompanyIdOpenapi,
        PathValues.V2_COMPANIES_COMPANY_ID_CUSTOMFIELDS_CATEGORY: V2CompaniesCompanyIdCustomfieldsCategory,
        PathValues.V2_COMPANIES_COMPANY_ID_EMPLOYEES_EMPLOYEE_ID_DIRECT_DEPOSIT: V2CompaniesCompanyIdEmployeesEmployeeIdDirectDeposit,
        PathValues.V2_COMPANIES_COMPANY_ID_EMPLOYEES_EMPLOYEE_ID_EARNINGS: V2CompaniesCompanyIdEmployeesEmployeeIdEarnings,
        PathValues.V2_COMPANIES_COMPANY_ID_EMPLOYEES_EMPLOYEE_ID_EARNINGS_EARNING_CODE_START_DATE: V2CompaniesCompanyIdEmployeesEmployeeIdEarningsEarningCodeStartDate,
        PathValues.V2_COMPANIES_COMPANY_ID_EMPLOYEES_EMPLOYEE_ID_EARNINGS_EARNING_CODE: V2CompaniesCompanyIdEmployeesEmployeeIdEarningsEarningCode,
        PathValues.V2_COMPANIES_COMPANY_ID_EMPLOYEES_EMPLOYEE_ID_EMERGENCY_CONTACTS: V2CompaniesCompanyIdEmployeesEmployeeIdEmergencyContacts,
        PathValues.V2_COMPANIES_COMPANY_ID_EMPLOYEES_EMPLOYEE_ID_BENEFIT_SETUP: V2CompaniesCompanyIdEmployeesEmployeeIdBenefitSetup,
        PathValues.V2_WEBLINKSTAGING_COMPANIES_COMPANY_ID_EMPLOYEES_NEWEMPLOYEES: V2WeblinkstagingCompaniesCompanyIdEmployeesNewemployees,
        PathValues.V2_COMPANIES_COMPANY_ID_EMPLOYEES: V2CompaniesCompanyIdEmployees,
        PathValues.V2_COMPANIES_COMPANY_ID_EMPLOYEES_EMPLOYEE_ID: V2CompaniesCompanyIdEmployeesEmployeeId,
        PathValues.V2_COMPANIES_COMPANY_ID_EMPLOYEES_EMPLOYEE_ID_LOCAL_TAXES: V2CompaniesCompanyIdEmployeesEmployeeIdLocalTaxes,
        PathValues.V2_COMPANIES_COMPANY_ID_EMPLOYEES_EMPLOYEE_ID_LOCAL_TAXES_TAX_CODE: V2CompaniesCompanyIdEmployeesEmployeeIdLocalTaxesTaxCode,
        PathValues.V2_COMPANIES_COMPANY_ID_EMPLOYEES_EMPLOYEE_ID_NONPRIMARY_STATE_TAX: V2CompaniesCompanyIdEmployeesEmployeeIdNonprimaryStateTax,
        PathValues.V2_COMPANIES_COMPANY_ID_EMPLOYEES_EMPLOYEE_ID_PAYSTATEMENT_DETAILS_YEAR_CHECK_DATE: V2CompaniesCompanyIdEmployeesEmployeeIdPaystatementDetailsYearCheckDate,
        PathValues.V2_COMPANIES_COMPANY_ID_EMPLOYEES_EMPLOYEE_ID_PAYSTATEMENT_DETAILS_YEAR: V2CompaniesCompanyIdEmployeesEmployeeIdPaystatementDetailsYear,
        PathValues.V2_COMPANIES_COMPANY_ID_EMPLOYEES_EMPLOYEE_ID_PAYSTATEMENT_SUMMARY_YEAR_CHECK_DATE: V2CompaniesCompanyIdEmployeesEmployeeIdPaystatementSummaryYearCheckDate,
        PathValues.V2_COMPANIES_COMPANY_ID_EMPLOYEES_EMPLOYEE_ID_PAYSTATEMENT_SUMMARY_YEAR: V2CompaniesCompanyIdEmployeesEmployeeIdPaystatementSummaryYear,
        PathValues.V2_COMPANIES_COMPANY_ID_EMPLOYEES_EMPLOYEE_ID_PRIMARY_STATE_TAX: V2CompaniesCompanyIdEmployeesEmployeeIdPrimaryStateTax,
        PathValues.V2_COMPANIES_COMPANY_ID_EMPLOYEES_EMPLOYEE_ID_SENSITIVEDATA: V2CompaniesCompanyIdEmployeesEmployeeIdSensitivedata,
    }
)

path_to_api = PathToApi(
    {
        PathValues.V1_EMPLOYEE: V1Employee,
        PathValues.V1_COMPANY_COMPANY_ID_EMPLOYEE_EMPLOYEE_ID: V1CompanyCompanyIdEmployeeEmployeeId,
        PathValues.V1_UPDATEEMPLOYEE: V1UpdateEmployee,
        PathValues.V1_DEDUCTION: V1Deduction,
        PathValues.V1_COMPANIES_COMPANY_ID_EMPLOYEES_EMPLOYEE_ID_DEDUCTIONS_DEDUCTION_CODE_START_DATE: V1CompaniesCompanyIdEmployeesEmployeeIdDeductionsDeductionCodeStartDate,
        PathValues.V1_COMPANIES_COMPANY_ID_EMPLOYEES_EMPLOYEE_ID_DEDUCTIONS: V1CompaniesCompanyIdEmployeesEmployeeIdDeductions,
        PathValues.V1_COMPANIES_COMPANY_ID_EMPLOYEES_EMPLOYEE_ID_DEDUCTIONS_DEDUCTION_CODE: V1CompaniesCompanyIdEmployeesEmployeeIdDeductionsDeductionCode,
        PathValues.V1_COMPANIES_COMPANY_ID_ONBOARDING_EMPLOYEES: V1CompaniesCompanyIdOnboardingEmployees,
        PathValues.V1_COMPANIES_COMPANY_ID_EMPLOYEES_EMPLOYEE_ID_LOCAL_TAXES_TAX_CODE: V1CompaniesCompanyIdEmployeesEmployeeIdLocalTaxesTaxCode,
        PathValues.V1_COMPANIES_COMPANY_ID_EMPLOYEES_EMPLOYEE_ID_LOCAL_TAXES: V1CompaniesCompanyIdEmployeesEmployeeIdLocalTaxes,
        PathValues.V2_COMPANIES_COMPANY_ID_EMPLOYEES_EMPLOYEE_ID_ADDITIONAL_RATES: V2CompaniesCompanyIdEmployeesEmployeeIdAdditionalRates,
        PathValues.V2_CREDENTIALS_SECRETS: V2CredentialsSecrets,
        PathValues.V2_COMPANIES_COMPANY_ID_CODES_CODE_RESOURCE: V2CompaniesCompanyIdCodesCodeResource,
        PathValues.V2_COMPANIES_COMPANY_ID_OPENAPI: V2CompaniesCompanyIdOpenapi,
        PathValues.V2_COMPANIES_COMPANY_ID_CUSTOMFIELDS_CATEGORY: V2CompaniesCompanyIdCustomfieldsCategory,
        PathValues.V2_COMPANIES_COMPANY_ID_EMPLOYEES_EMPLOYEE_ID_DIRECT_DEPOSIT: V2CompaniesCompanyIdEmployeesEmployeeIdDirectDeposit,
        PathValues.V2_COMPANIES_COMPANY_ID_EMPLOYEES_EMPLOYEE_ID_EARNINGS: V2CompaniesCompanyIdEmployeesEmployeeIdEarnings,
        PathValues.V2_COMPANIES_COMPANY_ID_EMPLOYEES_EMPLOYEE_ID_EARNINGS_EARNING_CODE_START_DATE: V2CompaniesCompanyIdEmployeesEmployeeIdEarningsEarningCodeStartDate,
        PathValues.V2_COMPANIES_COMPANY_ID_EMPLOYEES_EMPLOYEE_ID_EARNINGS_EARNING_CODE: V2CompaniesCompanyIdEmployeesEmployeeIdEarningsEarningCode,
        PathValues.V2_COMPANIES_COMPANY_ID_EMPLOYEES_EMPLOYEE_ID_EMERGENCY_CONTACTS: V2CompaniesCompanyIdEmployeesEmployeeIdEmergencyContacts,
        PathValues.V2_COMPANIES_COMPANY_ID_EMPLOYEES_EMPLOYEE_ID_BENEFIT_SETUP: V2CompaniesCompanyIdEmployeesEmployeeIdBenefitSetup,
        PathValues.V2_WEBLINKSTAGING_COMPANIES_COMPANY_ID_EMPLOYEES_NEWEMPLOYEES: V2WeblinkstagingCompaniesCompanyIdEmployeesNewemployees,
        PathValues.V2_COMPANIES_COMPANY_ID_EMPLOYEES: V2CompaniesCompanyIdEmployees,
        PathValues.V2_COMPANIES_COMPANY_ID_EMPLOYEES_EMPLOYEE_ID: V2CompaniesCompanyIdEmployeesEmployeeId,
        PathValues.V2_COMPANIES_COMPANY_ID_EMPLOYEES_EMPLOYEE_ID_LOCAL_TAXES: V2CompaniesCompanyIdEmployeesEmployeeIdLocalTaxes,
        PathValues.V2_COMPANIES_COMPANY_ID_EMPLOYEES_EMPLOYEE_ID_LOCAL_TAXES_TAX_CODE: V2CompaniesCompanyIdEmployeesEmployeeIdLocalTaxesTaxCode,
        PathValues.V2_COMPANIES_COMPANY_ID_EMPLOYEES_EMPLOYEE_ID_NONPRIMARY_STATE_TAX: V2CompaniesCompanyIdEmployeesEmployeeIdNonprimaryStateTax,
        PathValues.V2_COMPANIES_COMPANY_ID_EMPLOYEES_EMPLOYEE_ID_PAYSTATEMENT_DETAILS_YEAR_CHECK_DATE: V2CompaniesCompanyIdEmployeesEmployeeIdPaystatementDetailsYearCheckDate,
        PathValues.V2_COMPANIES_COMPANY_ID_EMPLOYEES_EMPLOYEE_ID_PAYSTATEMENT_DETAILS_YEAR: V2CompaniesCompanyIdEmployeesEmployeeIdPaystatementDetailsYear,
        PathValues.V2_COMPANIES_COMPANY_ID_EMPLOYEES_EMPLOYEE_ID_PAYSTATEMENT_SUMMARY_YEAR_CHECK_DATE: V2CompaniesCompanyIdEmployeesEmployeeIdPaystatementSummaryYearCheckDate,
        PathValues.V2_COMPANIES_COMPANY_ID_EMPLOYEES_EMPLOYEE_ID_PAYSTATEMENT_SUMMARY_YEAR: V2CompaniesCompanyIdEmployeesEmployeeIdPaystatementSummaryYear,
        PathValues.V2_COMPANIES_COMPANY_ID_EMPLOYEES_EMPLOYEE_ID_PRIMARY_STATE_TAX: V2CompaniesCompanyIdEmployeesEmployeeIdPrimaryStateTax,
        PathValues.V2_COMPANIES_COMPANY_ID_EMPLOYEES_EMPLOYEE_ID_SENSITIVEDATA: V2CompaniesCompanyIdEmployeesEmployeeIdSensitivedata,
    }
)
