# coding: utf-8

"""
    WebLink API

    For documentation about this API, please visit https://developer.paylocity.com/integrations/reference/weblink-overview

    The version of the OpenAPI document: v2
    Contact: webservices@paylocity.com
    Generated by: https://konfigthis.com
"""

import unittest

import paylocity_python_sdk
from paylocity_python_sdk.model.company_codes_get_all_by_resource404_response import CompanyCodesGetAllByResource404Response
from paylocity_python_sdk import configuration


class TestCompanyCodesGetAllByResource404Response(unittest.TestCase):
    """CompanyCodesGetAllByResource404Response unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
