# coding: utf-8

"""
    WebLink API

    For documentation about this API, please visit https://developer.paylocity.com/integrations/reference/weblink-overview

    The version of the OpenAPI document: v2
    Contact: webservices@paylocity.com
    Generated by: https://konfigthis.com
"""

import unittest

import paylocity_python_sdk
from paylocity_python_sdk.model.tracking_number_response import TrackingNumberResponse
from paylocity_python_sdk import configuration


class TestTrackingNumberResponse(unittest.TestCase):
    """TrackingNumberResponse unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
