# coding: utf-8

"""
    WebLink API

    For documentation about this API, please visit https://developer.paylocity.com/integrations/reference/weblink-overview

    The version of the OpenAPI document: v2
    Contact: webservices@paylocity.com
    Generated by: https://konfigthis.com
"""

from dataclasses import dataclass
import typing_extensions
import urllib3
from pydantic import RootModel
from paylocity_python_sdk.request_before_hook import request_before_hook
import json
from urllib3._collections import HTTPHeaderDict

from paylocity_python_sdk.api_response import AsyncGeneratorResponse
from paylocity_python_sdk import api_client, exceptions
from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from paylocity_python_sdk import schemas  # noqa: F401

from paylocity_python_sdk.model.errors import Errors as ErrorsSchema
from paylocity_python_sdk.model.onboarding import Onboarding as OnboardingSchema

from paylocity_python_sdk.type.onboarding import Onboarding
from paylocity_python_sdk.type.errors import Errors

from ...api_client import Dictionary
from paylocity_python_sdk.pydantic.onboarding import Onboarding as OnboardingPydantic
from paylocity_python_sdk.pydantic.errors import Errors as ErrorsPydantic

from . import path

# Path params
CompanyIdSchema = schemas.StrSchema
RequestRequiredPathParams = typing_extensions.TypedDict(
    'RequestRequiredPathParams',
    {
        'companyId': typing.Union[CompanyIdSchema, str, ],
    }
)
RequestOptionalPathParams = typing_extensions.TypedDict(
    'RequestOptionalPathParams',
    {
    },
    total=False
)


class RequestPathParams(RequestRequiredPathParams, RequestOptionalPathParams):
    pass


request_path_company_id = api_client.PathParameter(
    name="companyId",
    style=api_client.ParameterStyle.SIMPLE,
    schema=CompanyIdSchema,
    required=True,
)
# body param
SchemaForRequestBodyApplicationJson = OnboardingSchema


request_body_body = api_client.RequestBody(
    content={
        'application/json': api_client.MediaType(
            schema=SchemaForRequestBodyApplicationJson),
    },
    required=True,
)
_auth = [
    'paylocity_auth',
]


@dataclass
class ApiResponseFor201(api_client.ApiResponse):
    body: 


@dataclass
class ApiResponseFor201Async(api_client.AsyncApiResponse):
    body: 


_response_for_201 = api_client.OpenApiResponse(
    response_cls=ApiResponseFor201,
    response_cls_async=ApiResponseFor201Async,
)
SchemaFor400ResponseBodyApplicationJson = ErrorsSchema


@dataclass
class ApiResponseFor400(api_client.ApiResponse):
    body: Errors


@dataclass
class ApiResponseFor400Async(api_client.AsyncApiResponse):
    body: Errors


_response_for_400 = api_client.OpenApiResponse(
    response_cls=ApiResponseFor400,
    response_cls_async=ApiResponseFor400Async,
    content={
        'application/json': api_client.MediaType(
            schema=SchemaFor400ResponseBodyApplicationJson),
    },
)


@dataclass
class ApiResponseFor403(api_client.ApiResponse):
    body: 


@dataclass
class ApiResponseFor403Async(api_client.AsyncApiResponse):
    body: 


_response_for_403 = api_client.OpenApiResponse(
    response_cls=ApiResponseFor403,
    response_cls_async=ApiResponseFor403Async,
)
SchemaFor500ResponseBodyApplicationJson = ErrorsSchema


@dataclass
class ApiResponseFor500(api_client.ApiResponse):
    body: Errors


@dataclass
class ApiResponseFor500Async(api_client.AsyncApiResponse):
    body: Errors


_response_for_500 = api_client.OpenApiResponse(
    response_cls=ApiResponseFor500,
    response_cls_async=ApiResponseFor500Async,
    content={
        'application/json': api_client.MediaType(
            schema=SchemaFor500ResponseBodyApplicationJson),
    },
)
_status_code_to_response = {
    '201': _response_for_201,
    '400': _response_for_400,
    '403': _response_for_403,
    '500': _response_for_500,
}
_all_accept_content_types = (
    'application/json',
)


class BaseApi(api_client.Api):

    def _add_employee_to_onboarding_mapped_args(
        self,
        first_name: str,
        last_name: str,
        company_id: str,
        employee_id: typing.Optional[str] = None,
        address1: typing.Optional[str] = None,
        address2: typing.Optional[str] = None,
        auto_pay_type: typing.Optional[str] = None,
        base_rate: typing.Optional[typing.Union[int, float]] = None,
        city: typing.Optional[str] = None,
        cost_center1: typing.Optional[str] = None,
        cost_center2: typing.Optional[str] = None,
        cost_center3: typing.Optional[str] = None,
        default_hours: typing.Optional[typing.Union[int, float]] = None,
        employee_status: typing.Optional[str] = None,
        employment_type: typing.Optional[str] = None,
        federal_filing_status: typing.Optional[str] = None,
        sex: typing.Optional[str] = None,
        hire_date: typing.Optional[str] = None,
        home_phone: typing.Optional[str] = None,
        marital_status: typing.Optional[str] = None,
        personal_mobile_phone: typing.Optional[str] = None,
        pay_frequency: typing.Optional[str] = None,
        personal_email_address: typing.Optional[str] = None,
        pay_type: typing.Optional[str] = None,
        rate_per: typing.Optional[str] = None,
        salary: typing.Optional[typing.Union[int, float]] = None,
        state: typing.Optional[str] = None,
        ssn: typing.Optional[str] = None,
        state_filing_status: typing.Optional[str] = None,
        sui_state: typing.Optional[str] = None,
        tax_form: typing.Optional[str] = None,
        tax_state: typing.Optional[str] = None,
        user_name: typing.Optional[str] = None,
        work_email_address: typing.Optional[str] = None,
        zip: typing.Optional[str] = None,
    ) -> api_client.MappedArgs:
        args: api_client.MappedArgs = api_client.MappedArgs()
        _path_params = {}
        _body = {}
        if employee_id is not None:
            _body["employeeId"] = employee_id
        if address1 is not None:
            _body["address1"] = address1
        if address2 is not None:
            _body["address2"] = address2
        if auto_pay_type is not None:
            _body["autoPayType"] = auto_pay_type
        if base_rate is not None:
            _body["baseRate"] = base_rate
        if city is not None:
            _body["city"] = city
        if cost_center1 is not None:
            _body["costCenter1"] = cost_center1
        if cost_center2 is not None:
            _body["costCenter2"] = cost_center2
        if cost_center3 is not None:
            _body["costCenter3"] = cost_center3
        if default_hours is not None:
            _body["defaultHours"] = default_hours
        if employee_status is not None:
            _body["employeeStatus"] = employee_status
        if employment_type is not None:
            _body["employmentType"] = employment_type
        if federal_filing_status is not None:
            _body["federalFilingStatus"] = federal_filing_status
        if first_name is not None:
            _body["firstName"] = first_name
        if sex is not None:
            _body["sex"] = sex
        if hire_date is not None:
            _body["hireDate"] = hire_date
        if home_phone is not None:
            _body["homePhone"] = home_phone
        if last_name is not None:
            _body["lastName"] = last_name
        if marital_status is not None:
            _body["maritalStatus"] = marital_status
        if personal_mobile_phone is not None:
            _body["personalMobilePhone"] = personal_mobile_phone
        if pay_frequency is not None:
            _body["payFrequency"] = pay_frequency
        if personal_email_address is not None:
            _body["personalEmailAddress"] = personal_email_address
        if pay_type is not None:
            _body["payType"] = pay_type
        if rate_per is not None:
            _body["ratePer"] = rate_per
        if salary is not None:
            _body["salary"] = salary
        if state is not None:
            _body["state"] = state
        if ssn is not None:
            _body["ssn"] = ssn
        if state_filing_status is not None:
            _body["stateFilingStatus"] = state_filing_status
        if sui_state is not None:
            _body["suiState"] = sui_state
        if tax_form is not None:
            _body["taxForm"] = tax_form
        if tax_state is not None:
            _body["taxState"] = tax_state
        if user_name is not None:
            _body["userName"] = user_name
        if work_email_address is not None:
            _body["workEmailAddress"] = work_email_address
        if zip is not None:
            _body["zip"] = zip
        args.body = _body
        if company_id is not None:
            _path_params["companyId"] = company_id
        args.path = _path_params
        return args

    async def _aadd_employee_to_onboarding_oapg(
        self,
        body: typing.Any = None,
            path_params: typing.Optional[dict] = {},
        skip_deserialization: bool = True,
        timeout: typing.Optional[typing.Union[float, typing.Tuple]] = None,
        accept_content_types: typing.Tuple[str] = _all_accept_content_types,
        content_type: str = 'application/json',
        stream: bool = False,
        **kwargs,
    ) -> typing.Union[
        ApiResponseFor201Async,
        api_client.ApiResponseWithoutDeserializationAsync,
        AsyncGeneratorResponse,
    ]:
        """
        Add Employee to Onboarding
        :param skip_deserialization: If true then api_response.response will be set but
            api_response.body and api_response.headers will not be deserialized into schema
            class instances
        """
        self._verify_typed_dict_inputs_oapg(RequestPathParams, path_params)
        used_path = path.value
    
        _path_params = {}
        for parameter in (
            request_path_company_id,
        ):
            parameter_data = path_params.get(parameter.name, schemas.unset)
            if parameter_data is schemas.unset:
                continue
            serialized_data = parameter.serialize(parameter_data)
            _path_params.update(serialized_data)
    
        for k, v in _path_params.items():
            used_path = used_path.replace('{%s}' % k, v)
    
        _headers = HTTPHeaderDict()
        # TODO add cookie handling
        if accept_content_types:
            for accept_content_type in accept_content_types:
                _headers.add('Accept', accept_content_type)
        method = 'post'.upper()
        _headers.add('Content-Type', content_type)
    
        if body is schemas.unset:
            raise exceptions.ApiValueError(
                'The required body parameter has an invalid value of: unset. Set a valid value instead')
        _fields = None
        _body = None
        request_before_hook(
            resource_path=used_path,
            method=method,
            configuration=self.api_client.configuration,
            path_template='/v1/companies/{companyId}/onboarding/employees',
            body=body,
            auth_settings=_auth,
            headers=_headers,
        )
        serialized_data = request_body_body.serialize(body, content_type)
        if 'fields' in serialized_data:
            _fields = serialized_data['fields']
        elif 'body' in serialized_data:
            _body = serialized_data['body']
    
        response = await self.api_client.async_call_api(
            resource_path=used_path,
            method=method,
            headers=_headers,
            fields=_fields,
            serialized_body=_body,
            body=body,
            auth_settings=_auth,
            timeout=timeout,
            **kwargs
        )
    
        if stream:
            if not 200 <= response.http_response.status <= 299:
                body = (await response.http_response.content.read()).decode("utf-8")
                raise exceptions.ApiStreamingException(
                    status=response.http_response.status,
                    reason=response.http_response.reason,
                    body=body,
                )
    
            async def stream_iterator():
                """
                iterates over response.http_response.content and closes connection once iteration has finished
                """
                async for line in response.http_response.content:
                    if line == b'\r\n':
                        continue
                    yield line
                response.http_response.close()
                await response.session.close()
            return AsyncGeneratorResponse(
                content=stream_iterator(),
                headers=response.http_response.headers,
                status=response.http_response.status,
                response=response.http_response
            )
    
        response_for_status = _status_code_to_response.get(str(response.http_response.status))
        if response_for_status:
            api_response = await response_for_status.deserialize_async(
                                                    response,
                                                    self.api_client.configuration,
                                                    skip_deserialization=skip_deserialization
                                                )
        else:
            # If response data is JSON then deserialize for SDK consumer convenience
            is_json = api_client.JSONDetector._content_type_is_json(response.http_response.headers.get('Content-Type', ''))
            api_response = api_client.ApiResponseWithoutDeserializationAsync(
                body=await response.http_response.json() if is_json else await response.http_response.text(),
                response=response.http_response,
                round_trip_time=response.round_trip_time,
                status=response.http_response.status,
                headers=response.http_response.headers,
            )
    
        if not 200 <= api_response.status <= 299:
            raise exceptions.ApiException(api_response=api_response)
    
        # cleanup session / response
        response.http_response.close()
        await response.session.close()
    
        return api_response


    def _add_employee_to_onboarding_oapg(
        self,
        body: typing.Any = None,
            path_params: typing.Optional[dict] = {},
        skip_deserialization: bool = True,
        timeout: typing.Optional[typing.Union[float, typing.Tuple]] = None,
        accept_content_types: typing.Tuple[str] = _all_accept_content_types,
        content_type: str = 'application/json',
        stream: bool = False,
    ) -> typing.Union[
        ApiResponseFor201,
        api_client.ApiResponseWithoutDeserialization,
    ]:
        """
        Add Employee to Onboarding
        :param skip_deserialization: If true then api_response.response will be set but
            api_response.body and api_response.headers will not be deserialized into schema
            class instances
        """
        self._verify_typed_dict_inputs_oapg(RequestPathParams, path_params)
        used_path = path.value
    
        _path_params = {}
        for parameter in (
            request_path_company_id,
        ):
            parameter_data = path_params.get(parameter.name, schemas.unset)
            if parameter_data is schemas.unset:
                continue
            serialized_data = parameter.serialize(parameter_data)
            _path_params.update(serialized_data)
    
        for k, v in _path_params.items():
            used_path = used_path.replace('{%s}' % k, v)
    
        _headers = HTTPHeaderDict()
        # TODO add cookie handling
        if accept_content_types:
            for accept_content_type in accept_content_types:
                _headers.add('Accept', accept_content_type)
        method = 'post'.upper()
        _headers.add('Content-Type', content_type)
    
        if body is schemas.unset:
            raise exceptions.ApiValueError(
                'The required body parameter has an invalid value of: unset. Set a valid value instead')
        _fields = None
        _body = None
        request_before_hook(
            resource_path=used_path,
            method=method,
            configuration=self.api_client.configuration,
            path_template='/v1/companies/{companyId}/onboarding/employees',
            body=body,
            auth_settings=_auth,
            headers=_headers,
        )
        serialized_data = request_body_body.serialize(body, content_type)
        if 'fields' in serialized_data:
            _fields = serialized_data['fields']
        elif 'body' in serialized_data:
            _body = serialized_data['body']
    
        response = self.api_client.call_api(
            resource_path=used_path,
            method=method,
            headers=_headers,
            fields=_fields,
            serialized_body=_body,
            body=body,
            auth_settings=_auth,
            timeout=timeout,
        )
    
        response_for_status = _status_code_to_response.get(str(response.http_response.status))
        if response_for_status:
            api_response = response_for_status.deserialize(
                                                    response,
                                                    self.api_client.configuration,
                                                    skip_deserialization=skip_deserialization
                                                )
        else:
            # If response data is JSON then deserialize for SDK consumer convenience
            is_json = api_client.JSONDetector._content_type_is_json(response.http_response.headers.get('Content-Type', ''))
            api_response = api_client.ApiResponseWithoutDeserialization(
                body=json.loads(response.http_response.data) if is_json else response.http_response.data,
                response=response.http_response,
                round_trip_time=response.round_trip_time,
                status=response.http_response.status,
                headers=response.http_response.headers,
            )
    
        if not 200 <= api_response.status <= 299:
            raise exceptions.ApiException(api_response=api_response)
    
        return api_response


class AddEmployeeToOnboardingRaw(BaseApi):
    # this class is used by api classes that refer to endpoints with operationId fn names

    async def aadd_employee_to_onboarding(
        self,
        first_name: str,
        last_name: str,
        company_id: str,
        employee_id: typing.Optional[str] = None,
        address1: typing.Optional[str] = None,
        address2: typing.Optional[str] = None,
        auto_pay_type: typing.Optional[str] = None,
        base_rate: typing.Optional[typing.Union[int, float]] = None,
        city: typing.Optional[str] = None,
        cost_center1: typing.Optional[str] = None,
        cost_center2: typing.Optional[str] = None,
        cost_center3: typing.Optional[str] = None,
        default_hours: typing.Optional[typing.Union[int, float]] = None,
        employee_status: typing.Optional[str] = None,
        employment_type: typing.Optional[str] = None,
        federal_filing_status: typing.Optional[str] = None,
        sex: typing.Optional[str] = None,
        hire_date: typing.Optional[str] = None,
        home_phone: typing.Optional[str] = None,
        marital_status: typing.Optional[str] = None,
        personal_mobile_phone: typing.Optional[str] = None,
        pay_frequency: typing.Optional[str] = None,
        personal_email_address: typing.Optional[str] = None,
        pay_type: typing.Optional[str] = None,
        rate_per: typing.Optional[str] = None,
        salary: typing.Optional[typing.Union[int, float]] = None,
        state: typing.Optional[str] = None,
        ssn: typing.Optional[str] = None,
        state_filing_status: typing.Optional[str] = None,
        sui_state: typing.Optional[str] = None,
        tax_form: typing.Optional[str] = None,
        tax_state: typing.Optional[str] = None,
        user_name: typing.Optional[str] = None,
        work_email_address: typing.Optional[str] = None,
        zip: typing.Optional[str] = None,
        **kwargs,
    ) -> typing.Union[
        ApiResponseFor201Async,
        api_client.ApiResponseWithoutDeserializationAsync,
        AsyncGeneratorResponse,
    ]:
        args = self._add_employee_to_onboarding_mapped_args(
            first_name=first_name,
            last_name=last_name,
            company_id=company_id,
            employee_id=employee_id,
            address1=address1,
            address2=address2,
            auto_pay_type=auto_pay_type,
            base_rate=base_rate,
            city=city,
            cost_center1=cost_center1,
            cost_center2=cost_center2,
            cost_center3=cost_center3,
            default_hours=default_hours,
            employee_status=employee_status,
            employment_type=employment_type,
            federal_filing_status=federal_filing_status,
            sex=sex,
            hire_date=hire_date,
            home_phone=home_phone,
            marital_status=marital_status,
            personal_mobile_phone=personal_mobile_phone,
            pay_frequency=pay_frequency,
            personal_email_address=personal_email_address,
            pay_type=pay_type,
            rate_per=rate_per,
            salary=salary,
            state=state,
            ssn=ssn,
            state_filing_status=state_filing_status,
            sui_state=sui_state,
            tax_form=tax_form,
            tax_state=tax_state,
            user_name=user_name,
            work_email_address=work_email_address,
            zip=zip,
        )
        return await self._aadd_employee_to_onboarding_oapg(
            body=args.body,
            path_params=args.path,
            **kwargs,
        )
    
    def add_employee_to_onboarding(
        self,
        first_name: str,
        last_name: str,
        company_id: str,
        employee_id: typing.Optional[str] = None,
        address1: typing.Optional[str] = None,
        address2: typing.Optional[str] = None,
        auto_pay_type: typing.Optional[str] = None,
        base_rate: typing.Optional[typing.Union[int, float]] = None,
        city: typing.Optional[str] = None,
        cost_center1: typing.Optional[str] = None,
        cost_center2: typing.Optional[str] = None,
        cost_center3: typing.Optional[str] = None,
        default_hours: typing.Optional[typing.Union[int, float]] = None,
        employee_status: typing.Optional[str] = None,
        employment_type: typing.Optional[str] = None,
        federal_filing_status: typing.Optional[str] = None,
        sex: typing.Optional[str] = None,
        hire_date: typing.Optional[str] = None,
        home_phone: typing.Optional[str] = None,
        marital_status: typing.Optional[str] = None,
        personal_mobile_phone: typing.Optional[str] = None,
        pay_frequency: typing.Optional[str] = None,
        personal_email_address: typing.Optional[str] = None,
        pay_type: typing.Optional[str] = None,
        rate_per: typing.Optional[str] = None,
        salary: typing.Optional[typing.Union[int, float]] = None,
        state: typing.Optional[str] = None,
        ssn: typing.Optional[str] = None,
        state_filing_status: typing.Optional[str] = None,
        sui_state: typing.Optional[str] = None,
        tax_form: typing.Optional[str] = None,
        tax_state: typing.Optional[str] = None,
        user_name: typing.Optional[str] = None,
        work_email_address: typing.Optional[str] = None,
        zip: typing.Optional[str] = None,
    ) -> typing.Union[
        ApiResponseFor201,
        api_client.ApiResponseWithoutDeserialization,
    ]:
        args = self._add_employee_to_onboarding_mapped_args(
            first_name=first_name,
            last_name=last_name,
            company_id=company_id,
            employee_id=employee_id,
            address1=address1,
            address2=address2,
            auto_pay_type=auto_pay_type,
            base_rate=base_rate,
            city=city,
            cost_center1=cost_center1,
            cost_center2=cost_center2,
            cost_center3=cost_center3,
            default_hours=default_hours,
            employee_status=employee_status,
            employment_type=employment_type,
            federal_filing_status=federal_filing_status,
            sex=sex,
            hire_date=hire_date,
            home_phone=home_phone,
            marital_status=marital_status,
            personal_mobile_phone=personal_mobile_phone,
            pay_frequency=pay_frequency,
            personal_email_address=personal_email_address,
            pay_type=pay_type,
            rate_per=rate_per,
            salary=salary,
            state=state,
            ssn=ssn,
            state_filing_status=state_filing_status,
            sui_state=sui_state,
            tax_form=tax_form,
            tax_state=tax_state,
            user_name=user_name,
            work_email_address=work_email_address,
            zip=zip,
        )
        return self._add_employee_to_onboarding_oapg(
            body=args.body,
            path_params=args.path,
        )

class AddEmployeeToOnboarding(BaseApi):

    async def aadd_employee_to_onboarding(
        self,
        first_name: str,
        last_name: str,
        company_id: str,
        employee_id: typing.Optional[str] = None,
        address1: typing.Optional[str] = None,
        address2: typing.Optional[str] = None,
        auto_pay_type: typing.Optional[str] = None,
        base_rate: typing.Optional[typing.Union[int, float]] = None,
        city: typing.Optional[str] = None,
        cost_center1: typing.Optional[str] = None,
        cost_center2: typing.Optional[str] = None,
        cost_center3: typing.Optional[str] = None,
        default_hours: typing.Optional[typing.Union[int, float]] = None,
        employee_status: typing.Optional[str] = None,
        employment_type: typing.Optional[str] = None,
        federal_filing_status: typing.Optional[str] = None,
        sex: typing.Optional[str] = None,
        hire_date: typing.Optional[str] = None,
        home_phone: typing.Optional[str] = None,
        marital_status: typing.Optional[str] = None,
        personal_mobile_phone: typing.Optional[str] = None,
        pay_frequency: typing.Optional[str] = None,
        personal_email_address: typing.Optional[str] = None,
        pay_type: typing.Optional[str] = None,
        rate_per: typing.Optional[str] = None,
        salary: typing.Optional[typing.Union[int, float]] = None,
        state: typing.Optional[str] = None,
        ssn: typing.Optional[str] = None,
        state_filing_status: typing.Optional[str] = None,
        sui_state: typing.Optional[str] = None,
        tax_form: typing.Optional[str] = None,
        tax_state: typing.Optional[str] = None,
        user_name: typing.Optional[str] = None,
        work_email_address: typing.Optional[str] = None,
        zip: typing.Optional[str] = None,
        validate: bool = False,
        **kwargs,
    ) -> None:
        raw_response = await self.raw.aadd_employee_to_onboarding(
            first_name=first_name,
            last_name=last_name,
            company_id=company_id,
            employee_id=employee_id,
            address1=address1,
            address2=address2,
            auto_pay_type=auto_pay_type,
            base_rate=base_rate,
            city=city,
            cost_center1=cost_center1,
            cost_center2=cost_center2,
            cost_center3=cost_center3,
            default_hours=default_hours,
            employee_status=employee_status,
            employment_type=employment_type,
            federal_filing_status=federal_filing_status,
            sex=sex,
            hire_date=hire_date,
            home_phone=home_phone,
            marital_status=marital_status,
            personal_mobile_phone=personal_mobile_phone,
            pay_frequency=pay_frequency,
            personal_email_address=personal_email_address,
            pay_type=pay_type,
            rate_per=rate_per,
            salary=salary,
            state=state,
            ssn=ssn,
            state_filing_status=state_filing_status,
            sui_state=sui_state,
            tax_form=tax_form,
            tax_state=tax_state,
            user_name=user_name,
            work_email_address=work_email_address,
            zip=zip,
            **kwargs,
        )
    
    
    def add_employee_to_onboarding(
        self,
        first_name: str,
        last_name: str,
        company_id: str,
        employee_id: typing.Optional[str] = None,
        address1: typing.Optional[str] = None,
        address2: typing.Optional[str] = None,
        auto_pay_type: typing.Optional[str] = None,
        base_rate: typing.Optional[typing.Union[int, float]] = None,
        city: typing.Optional[str] = None,
        cost_center1: typing.Optional[str] = None,
        cost_center2: typing.Optional[str] = None,
        cost_center3: typing.Optional[str] = None,
        default_hours: typing.Optional[typing.Union[int, float]] = None,
        employee_status: typing.Optional[str] = None,
        employment_type: typing.Optional[str] = None,
        federal_filing_status: typing.Optional[str] = None,
        sex: typing.Optional[str] = None,
        hire_date: typing.Optional[str] = None,
        home_phone: typing.Optional[str] = None,
        marital_status: typing.Optional[str] = None,
        personal_mobile_phone: typing.Optional[str] = None,
        pay_frequency: typing.Optional[str] = None,
        personal_email_address: typing.Optional[str] = None,
        pay_type: typing.Optional[str] = None,
        rate_per: typing.Optional[str] = None,
        salary: typing.Optional[typing.Union[int, float]] = None,
        state: typing.Optional[str] = None,
        ssn: typing.Optional[str] = None,
        state_filing_status: typing.Optional[str] = None,
        sui_state: typing.Optional[str] = None,
        tax_form: typing.Optional[str] = None,
        tax_state: typing.Optional[str] = None,
        user_name: typing.Optional[str] = None,
        work_email_address: typing.Optional[str] = None,
        zip: typing.Optional[str] = None,
        validate: bool = False,
    ) -> None:
        raw_response = self.raw.add_employee_to_onboarding(
            first_name=first_name,
            last_name=last_name,
            company_id=company_id,
            employee_id=employee_id,
            address1=address1,
            address2=address2,
            auto_pay_type=auto_pay_type,
            base_rate=base_rate,
            city=city,
            cost_center1=cost_center1,
            cost_center2=cost_center2,
            cost_center3=cost_center3,
            default_hours=default_hours,
            employee_status=employee_status,
            employment_type=employment_type,
            federal_filing_status=federal_filing_status,
            sex=sex,
            hire_date=hire_date,
            home_phone=home_phone,
            marital_status=marital_status,
            personal_mobile_phone=personal_mobile_phone,
            pay_frequency=pay_frequency,
            personal_email_address=personal_email_address,
            pay_type=pay_type,
            rate_per=rate_per,
            salary=salary,
            state=state,
            ssn=ssn,
            state_filing_status=state_filing_status,
            sui_state=sui_state,
            tax_form=tax_form,
            tax_state=tax_state,
            user_name=user_name,
            work_email_address=work_email_address,
            zip=zip,
        )


class ApiForpost(BaseApi):
    # this class is used by api classes that refer to endpoints by path and http method names

    async def apost(
        self,
        first_name: str,
        last_name: str,
        company_id: str,
        employee_id: typing.Optional[str] = None,
        address1: typing.Optional[str] = None,
        address2: typing.Optional[str] = None,
        auto_pay_type: typing.Optional[str] = None,
        base_rate: typing.Optional[typing.Union[int, float]] = None,
        city: typing.Optional[str] = None,
        cost_center1: typing.Optional[str] = None,
        cost_center2: typing.Optional[str] = None,
        cost_center3: typing.Optional[str] = None,
        default_hours: typing.Optional[typing.Union[int, float]] = None,
        employee_status: typing.Optional[str] = None,
        employment_type: typing.Optional[str] = None,
        federal_filing_status: typing.Optional[str] = None,
        sex: typing.Optional[str] = None,
        hire_date: typing.Optional[str] = None,
        home_phone: typing.Optional[str] = None,
        marital_status: typing.Optional[str] = None,
        personal_mobile_phone: typing.Optional[str] = None,
        pay_frequency: typing.Optional[str] = None,
        personal_email_address: typing.Optional[str] = None,
        pay_type: typing.Optional[str] = None,
        rate_per: typing.Optional[str] = None,
        salary: typing.Optional[typing.Union[int, float]] = None,
        state: typing.Optional[str] = None,
        ssn: typing.Optional[str] = None,
        state_filing_status: typing.Optional[str] = None,
        sui_state: typing.Optional[str] = None,
        tax_form: typing.Optional[str] = None,
        tax_state: typing.Optional[str] = None,
        user_name: typing.Optional[str] = None,
        work_email_address: typing.Optional[str] = None,
        zip: typing.Optional[str] = None,
        **kwargs,
    ) -> typing.Union[
        ApiResponseFor201Async,
        api_client.ApiResponseWithoutDeserializationAsync,
        AsyncGeneratorResponse,
    ]:
        args = self._add_employee_to_onboarding_mapped_args(
            first_name=first_name,
            last_name=last_name,
            company_id=company_id,
            employee_id=employee_id,
            address1=address1,
            address2=address2,
            auto_pay_type=auto_pay_type,
            base_rate=base_rate,
            city=city,
            cost_center1=cost_center1,
            cost_center2=cost_center2,
            cost_center3=cost_center3,
            default_hours=default_hours,
            employee_status=employee_status,
            employment_type=employment_type,
            federal_filing_status=federal_filing_status,
            sex=sex,
            hire_date=hire_date,
            home_phone=home_phone,
            marital_status=marital_status,
            personal_mobile_phone=personal_mobile_phone,
            pay_frequency=pay_frequency,
            personal_email_address=personal_email_address,
            pay_type=pay_type,
            rate_per=rate_per,
            salary=salary,
            state=state,
            ssn=ssn,
            state_filing_status=state_filing_status,
            sui_state=sui_state,
            tax_form=tax_form,
            tax_state=tax_state,
            user_name=user_name,
            work_email_address=work_email_address,
            zip=zip,
        )
        return await self._aadd_employee_to_onboarding_oapg(
            body=args.body,
            path_params=args.path,
            **kwargs,
        )
    
    def post(
        self,
        first_name: str,
        last_name: str,
        company_id: str,
        employee_id: typing.Optional[str] = None,
        address1: typing.Optional[str] = None,
        address2: typing.Optional[str] = None,
        auto_pay_type: typing.Optional[str] = None,
        base_rate: typing.Optional[typing.Union[int, float]] = None,
        city: typing.Optional[str] = None,
        cost_center1: typing.Optional[str] = None,
        cost_center2: typing.Optional[str] = None,
        cost_center3: typing.Optional[str] = None,
        default_hours: typing.Optional[typing.Union[int, float]] = None,
        employee_status: typing.Optional[str] = None,
        employment_type: typing.Optional[str] = None,
        federal_filing_status: typing.Optional[str] = None,
        sex: typing.Optional[str] = None,
        hire_date: typing.Optional[str] = None,
        home_phone: typing.Optional[str] = None,
        marital_status: typing.Optional[str] = None,
        personal_mobile_phone: typing.Optional[str] = None,
        pay_frequency: typing.Optional[str] = None,
        personal_email_address: typing.Optional[str] = None,
        pay_type: typing.Optional[str] = None,
        rate_per: typing.Optional[str] = None,
        salary: typing.Optional[typing.Union[int, float]] = None,
        state: typing.Optional[str] = None,
        ssn: typing.Optional[str] = None,
        state_filing_status: typing.Optional[str] = None,
        sui_state: typing.Optional[str] = None,
        tax_form: typing.Optional[str] = None,
        tax_state: typing.Optional[str] = None,
        user_name: typing.Optional[str] = None,
        work_email_address: typing.Optional[str] = None,
        zip: typing.Optional[str] = None,
    ) -> typing.Union[
        ApiResponseFor201,
        api_client.ApiResponseWithoutDeserialization,
    ]:
        args = self._add_employee_to_onboarding_mapped_args(
            first_name=first_name,
            last_name=last_name,
            company_id=company_id,
            employee_id=employee_id,
            address1=address1,
            address2=address2,
            auto_pay_type=auto_pay_type,
            base_rate=base_rate,
            city=city,
            cost_center1=cost_center1,
            cost_center2=cost_center2,
            cost_center3=cost_center3,
            default_hours=default_hours,
            employee_status=employee_status,
            employment_type=employment_type,
            federal_filing_status=federal_filing_status,
            sex=sex,
            hire_date=hire_date,
            home_phone=home_phone,
            marital_status=marital_status,
            personal_mobile_phone=personal_mobile_phone,
            pay_frequency=pay_frequency,
            personal_email_address=personal_email_address,
            pay_type=pay_type,
            rate_per=rate_per,
            salary=salary,
            state=state,
            ssn=ssn,
            state_filing_status=state_filing_status,
            sui_state=sui_state,
            tax_form=tax_form,
            tax_state=tax_state,
            user_name=user_name,
            work_email_address=work_email_address,
            zip=zip,
        )
        return self._add_employee_to_onboarding_oapg(
            body=args.body,
            path_params=args.path,
        )

