# coding: utf-8

"""
    WebLink API

    For documentation about this API, please visit https://developer.paylocity.com/integrations/reference/weblink-overview

    The version of the OpenAPI document: v2
    Contact: webservices@paylocity.com
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel

from paylocity_python_sdk.pydantic.add_update_deduction import AddUpdateDeduction

class DeductionAddOrUpdateDeductionRequest(BaseModel):
    deduction: typing.Optional[AddUpdateDeduction] = Field(None, alias='deduction')
    class Config:
        arbitrary_types_allowed = True
