# coding: utf-8

"""
    WebLink API

    For documentation about this API, please visit https://developer.paylocity.com/integrations/reference/weblink-overview

    The version of the OpenAPI document: v2
    Contact: webservices@paylocity.com
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel

from paylocity_python_sdk.pydantic.new_employee import NewEmployee

class EmployeeV1CreateNewEmployeeRecordRequest(BaseModel):
    new_employee: typing.Optional[NewEmployee] = Field(None, alias='newEmployee')
    class Config:
        arbitrary_types_allowed = True
