# coding: utf-8

"""
    WebLink API

    For documentation about this API, please visit https://developer.paylocity.com/integrations/reference/weblink-overview

    The version of the OpenAPI document: v2
    Contact: webservices@paylocity.com
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel

from paylocity_python_sdk.pydantic.employee_additional_direct_deposit import EmployeeAdditionalDirectDeposit
from paylocity_python_sdk.pydantic.employee_additional_rate import EmployeeAdditionalRate
from paylocity_python_sdk.pydantic.employee_custom_boolean_fields import EmployeeCustomBooleanFields
from paylocity_python_sdk.pydantic.employee_custom_date_fields import EmployeeCustomDateFields
from paylocity_python_sdk.pydantic.employee_custom_drop_down_fields import EmployeeCustomDropDownFields
from paylocity_python_sdk.pydantic.employee_custom_number_fields import EmployeeCustomNumberFields
from paylocity_python_sdk.pydantic.employee_custom_text_fields import EmployeeCustomTextFields
from paylocity_python_sdk.pydantic.employee_emergency_contacts import EmployeeEmergencyContacts
from paylocity_python_sdk.pydantic.employee_local_tax import EmployeeLocalTax

class Employee(BaseModel):
    additional_direct_deposit: typing.Optional[EmployeeAdditionalDirectDeposit] = Field(None, alias='additionalDirectDeposit')

    additional_rate: typing.Optional[EmployeeAdditionalRate] = Field(None, alias='additionalRate')

    #  Add or update setup values used for employee benefits integration, insurance plan settings, and ACA reporting.
    benefit_setup: typing.Optional[typing.Dict[str, typing.Union[bool, date, datetime, dict, float, int, list, str, None]]] = Field(None, alias='benefitSetup')

    # Employee birthdate. Common formats include *MM-DD-CCYY*, *CCYY-MM-DD*.
    birth_date: typing.Optional[typing.Dict[str, typing.Union[bool, date, datetime, dict, float, int, list, str, None]]] = Field(None, alias='birthDate')

    # Company FEIN as defined in Paylocity Payroll/HR solution, applicable with GET requests only.<br  /> Max length: 20
    company_f_e_i_n: typing.Optional[typing.Dict[str, typing.Union[bool, date, datetime, dict, float, int, list, str, None]]] = Field(None, alias='companyFEIN')

    # Company name as defined in Paylocity Payroll/HR solution, applicable with GET requests only.<br  /> Max length: 50
    company_name: typing.Optional[typing.Dict[str, typing.Union[bool, date, datetime, dict, float, int, list, str, None]]] = Field(None, alias='companyName')

    # Employee is paid in this currency. <br  />Max length: 30
    currency: typing.Optional[typing.Dict[str, typing.Union[bool, date, datetime, dict, float, int, list, str, None]]] = Field(None, alias='currency')

    custom_boolean_fields: typing.Optional[EmployeeCustomBooleanFields] = Field(None, alias='customBooleanFields')

    custom_date_fields: typing.Optional[EmployeeCustomDateFields] = Field(None, alias='customDateFields')

    custom_drop_down_fields: typing.Optional[EmployeeCustomDropDownFields] = Field(None, alias='customDropDownFields')

    custom_number_fields: typing.Optional[EmployeeCustomNumberFields] = Field(None, alias='customNumberFields')

    custom_text_fields: typing.Optional[EmployeeCustomTextFields] = Field(None, alias='customTextFields')

    # Add or update home department cost center, position, supervisor, reviewer, employment type, EEO class, pay settings, and union information.
    department_position: typing.Optional[typing.Dict[str, typing.Union[bool, date, datetime, dict, float, int, list, str, None]]] = Field(None, alias='departmentPosition')

    # Indicates if employee has disability status.
    disability_description: typing.Optional[typing.Dict[str, typing.Union[bool, date, datetime, dict, float, int, list, str, None]]] = Field(None, alias='disabilityDescription')

    emergency_contacts: typing.Optional[EmployeeEmergencyContacts] = Field(None, alias='emergencyContacts')

    # Leave blank to have Paylocity Payroll/HR solution automatically assign the next available employee ID.<br  />Max length: 10
    employee_id: typing.Optional[typing.Dict[str, typing.Union[bool, date, datetime, dict, float, int, list, str, None]]] = Field(None, alias='employeeId')

    # Employee ethnicity.<br  /> Max length: 10
    ethnicity: typing.Optional[typing.Dict[str, typing.Union[bool, date, datetime, dict, float, int, list, str, None]]] = Field(None, alias='ethnicity')

    # Add or update federal tax amount type (taxCalculationCode), amount or percentage, filing status, and exemptions.
    federal_tax: typing.Optional[typing.Dict[str, typing.Union[bool, date, datetime, dict, float, int, list, str, None]]] = Field(None, alias='federalTax')

    # Employee first name. <br  />Max length: 40
    first_name: typing.Optional[typing.Dict[str, typing.Union[bool, date, datetime, dict, float, int, list, str, None]]] = Field(None, alias='firstName')

    # Employee gender. Common values *M* (Male), *F* (Female). <br  />Max length: 1
    gender: typing.Optional[typing.Dict[str, typing.Union[bool, date, datetime, dict, float, int, list, str, None]]] = Field(None, alias='gender')

    # Add or update employee's home address, personal phone numbers, and personal email.
    home_address: typing.Optional[typing.Dict[str, typing.Union[bool, date, datetime, dict, float, int, list, str, None]]] = Field(None, alias='homeAddress')

    # Indicates if employee meets the highly compensated employee criteria.
    is_highly_compensated: typing.Optional[bool] = Field(None, alias='isHighlyCompensated')

    # Indicates if employee is a smoker.
    is_smoker: typing.Optional[bool] = Field(None, alias='isSmoker')

    # Employee last name. <br  />Max length: 40
    last_name: typing.Optional[typing.Dict[str, typing.Union[bool, date, datetime, dict, float, int, list, str, None]]] = Field(None, alias='lastName')

    local_tax: typing.Optional[EmployeeLocalTax] = Field(None, alias='localTax')

    # Add the main direct deposit account. After deposits are made to any additional direct deposit accounts, the remaining net check is deposited in the main direct deposit account. IMPORTANT: A direct deposit update will remove ALL existing main and additional direct deposit information in WebPay and replace with what is provided on the request. GET API will not return direct deposit data.
    main_direct_deposit: typing.Optional[typing.Dict[str, typing.Union[bool, date, datetime, dict, float, int, list, str, None]]] = Field(None, alias='mainDirectDeposit')

    # Employee marital status. Common values *D (Divorced), M (Married), S (Single), W (Widowed)*. <br  />Max length: 10
    marital_status: typing.Optional[typing.Dict[str, typing.Union[bool, date, datetime, dict, float, int, list, str, None]]] = Field(None, alias='maritalStatus')

    # Employee middle name.<br  /> Max length: 20
    middle_name: typing.Optional[typing.Dict[str, typing.Union[bool, date, datetime, dict, float, int, list, str, None]]] = Field(None, alias='middleName')

    # Add or update non-primary state tax code, amount type (taxCalculationCode), amount or percentage, filing status, exemptions, supplemental check (specialCheckCalc), and reciprocity code information.
    non_primary_state_tax: typing.Optional[typing.Dict[str, typing.Union[bool, date, datetime, dict, float, int, list, str, None]]] = Field(None, alias='nonPrimaryStateTax')

    # Percentage of employee's ownership in the company, entered as a whole number. <br  /> Decimal (12,2)
    owner_percent: typing.Optional[typing.Dict[str, typing.Union[bool, date, datetime, dict, float, int, list, str, None]]] = Field(None, alias='ownerPercent')

    # Employee preferred display name.<br  /> Max length: 20
    preferred_name: typing.Optional[typing.Dict[str, typing.Union[bool, date, datetime, dict, float, int, list, str, None]]] = Field(None, alias='preferredName')

    # Add or update hourly or salary pay rate, effective date, and pay frequency.
    primary_pay_rate: typing.Optional[typing.Dict[str, typing.Union[bool, date, datetime, dict, float, int, list, str, None]]] = Field(None, alias='primaryPayRate')

    # Add or update primary state tax code, amount type (taxCalculationCode), amount or percentage, filing status, exemptions, and supplemental check (specialCheckCalc) information. Only one primary state is allowed. Sending an updated primary state will replace the current primary state.
    primary_state_tax: typing.Optional[typing.Dict[str, typing.Union[bool, date, datetime, dict, float, int, list, str, None]]] = Field(None, alias='primaryStateTax')

    # Prior last name if applicable.<br  />Max length: 40
    prior_last_name: typing.Optional[typing.Dict[str, typing.Union[bool, date, datetime, dict, float, int, list, str, None]]] = Field(None, alias='priorLastName')

    # Employee preferred salutation. <br  />Max length: 10
    salutation: typing.Optional[typing.Dict[str, typing.Union[bool, date, datetime, dict, float, int, list, str, None]]] = Field(None, alias='salutation')

    # Employee social security number. Leave it blank if valid social security number not available. <br  />Max length: 11
    ssn: typing.Optional[typing.Dict[str, typing.Union[bool, date, datetime, dict, float, int, list, str, None]]] = Field(None, alias='ssn')

    # Add or update employee status, change reason, effective date, and adjusted seniority date. Note that companies that are still in Implementation cannot hire future employees.
    status: typing.Optional[typing.Dict[str, typing.Union[bool, date, datetime, dict, float, int, list, str, None]]] = Field(None, alias='status')

    # Employee name suffix. Common values are *Jr, Sr, II*.<br  />Max length: 30
    suffix: typing.Optional[typing.Dict[str, typing.Union[bool, date, datetime, dict, float, int, list, str, None]]] = Field(None, alias='suffix')

    # Add tax form, 1099 exempt reasons and notes, and 943 agricultural employee information. Once the employee receives wages, this information cannot be updated. Add or update SUI tax state, retirement plan, and statutory information.
    tax_setup: typing.Optional[typing.Dict[str, typing.Union[bool, date, datetime, dict, float, int, list, str, None]]] = Field(None, alias='taxSetup')

    # Indicates if employee is a veteran.
    veteran_description: typing.Optional[typing.Dict[str, typing.Union[bool, date, datetime, dict, float, int, list, str, None]]] = Field(None, alias='veteranDescription')

    # Add or update Web Time badge number and charge rate and synchronize Paylocity Payroll/HR solution and Web Time employee data.
    web_time: typing.Optional[typing.Dict[str, typing.Union[bool, date, datetime, dict, float, int, list, str, None]]] = Field(None, alias='webTime')

    # Add or update employee's work address, phone numbers, and email. Work Location drop down field is not included.
    work_address: typing.Optional[typing.Dict[str, typing.Union[bool, date, datetime, dict, float, int, list, str, None]]] = Field(None, alias='workAddress')

    # Add or update I-9 work authorization information.
    work_eligibility: typing.Optional[typing.Dict[str, typing.Union[bool, date, datetime, dict, float, int, list, str, None]]] = Field(None, alias='workEligibility')
    class Config:
        arbitrary_types_allowed = True
