# coding: utf-8

"""
    WebLink API

    For documentation about this API, please visit https://developer.paylocity.com/integrations/reference/weblink-overview

    The version of the OpenAPI document: v2
    Contact: webservices@paylocity.com
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel


class EmployeeV1BenefitSetup(BaseModel):
    # Benefit Class code. Values are configured in Paylocity Payroll/HR solution Company > Setup > Benefits > Classes.<br  />Max length: 30
    benefit_class: typing.Optional[str] = Field(None, alias='benefitClass')

    # Date when Benefit Class takes effect. Common formats are *MM-DD-CCYY, CCYY-MM-DD*.
    benefit_class_effective_date: typing.Optional[str] = Field(None, alias='benefitClassEffectiveDate')

    # Salary used to configure benefits.<br  />Decimal(12,2)
    benefit_salary: typing.Optional[typing.Union[int, float]] = Field(None, alias='benefitSalary')

    # Date when Benefit Salary takes effect. Common formats are *MM-DD-CCYY, CCYY-MM-DD*.
    benefit_salary_effective_date: typing.Optional[str] = Field(None, alias='benefitSalaryEffectiveDate')

    # Applicable only for ACA Enhanced clients and Benefit Classes with ACA Employment Type of Full Time.
    do_not_apply_administrative_period: typing.Optional[bool] = Field(None, alias='doNotApplyAdministrativePeriod')

    # Only valid for ACA Enhanced clients and Benefit Classes that are ACA Employment Type of Full Time.
    measure_a_c_a_eligibility: typing.Optional[bool] = Field(None, alias='measureACAEligibility')
    class Config:
        arbitrary_types_allowed = True
