# coding: utf-8

"""
    WebLink API

    For documentation about this API, please visit https://developer.paylocity.com/integrations/reference/weblink-overview

    The version of the OpenAPI document: v2
    Contact: webservices@paylocity.com
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel


class NewWorkEligibility(BaseModel):
    # Employee USCIS or Admission Number. <br  /> Must be 7-10 characters and may begin with an 'A'
    alien_or_admission_document_nbr: typing.Optional[str] = Field(None, alias='alienOrAdmissionDocumentNbr')

    # The date Employee I9 was verified by the employer. Common formats are *MM-DD-CCYY, CCYY-MM-DD*.
    i9_date_verified: typing.Optional[date] = Field(None, alias='i9DateVerified')

    # Notes regarding employee's I9.<br  /> Max length: 4000
    i9_notes: typing.Optional[str] = Field(None, alias='i9Notes')

    # Indicates if employee I9 is verified.
    i9_verified: typing.Optional[bool] = Field(None, alias='i9Verified')

    # The date of employer verification of employee SSN. Common formats are *MM-DD-CCYY, CCYY-MM-DD*.
    s_s_n_date_verified: typing.Optional[date] = Field(None, alias='sSNDateVerified')

    # Notes regarding employee's SSN.<br  /> Max length: 4000
    s_s_n_notes: typing.Optional[str] = Field(None, alias='sSNNotes')

    # Indicates if employee SSN is verified.
    s_s_n_verified: typing.Optional[bool] = Field(None, alias='sSNVerified')

    # Employee Visa type. Must match one of the system coded values.<br  /> Max length: 100
    visa_type: typing.Optional[str] = Field(None, alias='visaType')

    # Employee work authorization. Must match one of the system coded values.<br  /> Max length: 100
    work_authorization: typing.Optional[str] = Field(None, alias='workAuthorization')

    # End date of employee work eligibility. Common formats are *MM-DD-CCYY, CCYY-MM-DD*.
    work_until: typing.Optional[date] = Field(None, alias='workUntil')

    # The date the I-9 Verification form was attested by Employer or Authorized representative. Common formats are *MM-DD-CCYY, CCYY-MM-DD*.
    attested_date: typing.Optional[date] = Field(None, alias='attestedDate')

    # Form I-94 admission number.<br  /> Must be 11 numeric characters.
    i94_admission_number: typing.Optional[str] = Field(None, alias='i94AdmissionNumber')

    # Foreign Passport Number.<br  /> Max length: 50
    foreign_passport_number: typing.Optional[str] = Field(None, alias='foreignPassportNumber')

    # If Foreign Passport number is provided, provide its country of issuance. Must match Paylocity setup.<br  /> Max length: 30
    country_of_issuance: typing.Optional[str] = Field(None, alias='countryOfIssuance')
    class Config:
        arbitrary_types_allowed = True
