# coding: utf-8

"""
    WebLink API

    For documentation about this API, please visit https://developer.paylocity.com/integrations/reference/weblink-overview

    The version of the OpenAPI document: v2
    Contact: webservices@paylocity.com
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from paylocity_python_sdk.type.employee_v1_benefit_setup import EmployeeV1BenefitSetup
from paylocity_python_sdk.type.employee_v1_department_position import EmployeeV1DepartmentPosition
from paylocity_python_sdk.type.employee_v1_employee_status import EmployeeV1EmployeeStatus
from paylocity_python_sdk.type.employee_v1_primary_pay_rate import EmployeeV1PrimaryPayRate

class RequiredEmployeeV1(TypedDict):
    pass

class OptionalEmployeeV1(TypedDict, total=False):
    # Employee home 1st address line. <br  />Max length: 40
    address1: str

    # Employee home 2nd address line. <br  />Max length: 40
    address2: str

    benefitSetup: EmployeeV1BenefitSetup

    # Employee birthdate. Common formats are *MM-DD-CCYY, CCYY-MM-DD*.
    birthDate: str

    # Employee home city. <br  />Max length: 40
    city: str

    # Paylocity assigned company number. <br  /> Max length: 9
    companyNumber: str

    departmentPosition: EmployeeV1DepartmentPosition

    # Leave blank to have Paylocity Payroll/HR solution automatically assign the next available employee ID.<br  /> Max length: 10
    employeeId: str

    employeeStatus: EmployeeV1EmployeeStatus

    # Employee ethnicity.<br  /> Max length: 10
    ethnicity: str

    # Employee first name. <br  />Max length: 40
    firstName: str

    # Employee gender. Common values *M* (Male), *F* (Female). <br  />Max length: 1
    gender: str

    # Indicates if employee meets the highly compensated employee criteria.
    highlyCompensatedEmployee: bool

    # Employee hired date. Common formats are *MM-DD-CCYY, CCYY-MM-DD*.
    hireDate: str

    # Employee home phone number.  <br  />Max length: 12
    homePhone: str

    # Employee last name. <br  />Max length: 40
    lastName: str

    # Employee marital status. Common values *D (Divorced), M (Married), S (Single), W (Widowed)*. <br  />Max length: 10
    maritalStatus: str

    # Employee middle name.<br  /> Max length: 20
    middleName: str

    # Employee preferred display name. <br  /> Max length: 20
    nickname: str

    # Percentage of employee's ownership in the company, entered as a whole number . <br  /> Decimal (12,2)
    ownerPercent: typing.Union[int, float]

    # Employee personal email address. <br  />Max length: 50
    personalEmailAddress: str

    # Employee personal mobile phone number. <br  />Max length: 12
    personalMobilePhone: str

    # Employee position code. Must match Company setup.<br  />Max length: 20 
    position: str

    # Employee work zip code.<br  /> Max length: 10
    postalCode: str

    primaryPayRate: EmployeeV1PrimaryPayRate

    # Rehire date if employee is rehired. Common formats are *MM-DD-CCYY, CCYY-MM-DD*.
    reHireDate: str

    # Employee social security number. Leave it blank if valid social security number not available. <br  />Max length: 11
    ssn: str

    # Employee home state. <br  />Max length: 2
    state: str

    # Indicates if employee is statutory.
    statutory: bool

    # Supervisor's company number. Defaults to employee company number.<br  />Max length: 9
    supervisorCompanyNumber: str

    # EmployeeId of the supervisor. <br  />Max length: 10
    supervisorEmployeeId: str

    # Employee tax form for reporting income. Valid values are *W2, 1099M, 1099R*. Default is W2. <br  />Max length: 15
    taxForm: str

    # Date of emplyee termination. Common formats are *MM-DD-CCYY, CCYY-MM-DD*.
    terminationDate: str

    # Employee termination reason. Must match Company setup for employee status.<br  />Max length: 15
    terminationReason: str

    # Employee work email. <br  />Max length: 50
    workEmailAddress: str

    # Employee work phone number.<br  /> Max length: 12
    workPhone: str

    # Employee work phone extension number.<br  /> Max length: 10
    workPhoneExt: str

class EmployeeV1(RequiredEmployeeV1, OptionalEmployeeV1):
    pass
