# coding: utf-8

"""
    WebLink API

    For documentation about this API, please visit https://developer.paylocity.com/integrations/reference/weblink-overview

    The version of the OpenAPI document: v2
    Contact: webservices@paylocity.com
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from paylocity_python_sdk.type.update_employee import UpdateEmployee

class RequiredEmployeeV1UpdateEmployeeDataToPaylocityRequest(TypedDict):
    pass

class OptionalEmployeeV1UpdateEmployeeDataToPaylocityRequest(TypedDict, total=False):
    updateEmployee: UpdateEmployee

class EmployeeV1UpdateEmployeeDataToPaylocityRequest(RequiredEmployeeV1UpdateEmployeeDataToPaylocityRequest, OptionalEmployeeV1UpdateEmployeeDataToPaylocityRequest):
    pass
