# coding: utf-8

"""
    WebLink API

    For documentation about this API, please visit https://developer.paylocity.com/integrations/reference/weblink-overview

    The version of the OpenAPI document: v2
    Contact: webservices@paylocity.com
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from paylocity_python_sdk.type.error_options import ErrorOptions

class RequiredError(TypedDict):
    pass

class OptionalError(TypedDict, total=False):
    # The name of the field, or property in the request message that contains an error.
    field: str

    # The error message.
    message: str

    options: ErrorOptions

    # The JSON path of the field, or property, that contains an error in the request message.
    path: str

class Error(RequiredError, OptionalError):
    pass
